name = "hinatama-line-worker"
main = "src/index.ts"
compatibility_date = "2024-12-01"
workers_dev = true

[vars]
WORKER_URL = "https://hinatama-line-worker.sogadaiki.workers.dev"
SCOPED_LINE_ACCOUNT_ID = "22920358-e4eb-4878-bfa2-f6bf97fcb4fa"

[assets]
directory = "dist/client"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "sadame-line-crm"
database_id = "973f09e0-a762-434e-9861-07279a28510e"

[triggers]
crons = ["*/5 * * * *"]
